// TUMAINI CARE — Kenya Counties and Sub-Counties
// Source: Kenya National Bureau of Statistics / Ministry of Health
// All 47 counties with official sub-counties

export const KENYA_COUNTIES = {
  "Mombasa": ["Changamwe","Jomvu","Kisauni","Likoni","Mvita","Nyali"],
  "Kwale": ["Kinango","Lungalunga","Msambweni","Matuga"],
  "Kilifi": ["Ganze","Kaloleni","Kilifi North","Kilifi South","Magarini","Malindi","Rabai"],
  "Tana River": ["Bura","Galole","Garsen"],
  "Lamu": ["Lamu East","Lamu West"],
  "Taita Taveta": ["Mwatate","Taveta","Voi","Wundanyi"],
  "Garissa": ["Daadab","Fafi","Garissa Township","Hulugho","Ijara","Lagdera"],
  "Wajir": ["Eldas","Tarbaj","Wajir East","Wajir North","Wajir South","Wajir West"],
  "Mandera": ["Banissa","Lafey","Mandera East","Mandera North","Mandera South","Mandera West"],
  "Marsabit": ["Laisamis","Moyale","North Horr","Saku"],
  "Isiolo": ["Garbatulla","Isiolo","Merti"],
  "Meru": ["Buuri","Igembe Central","Igembe North","Igembe South","Imenti Central","Imenti North","Imenti South","Tigania East","Tigania West"],
  "Tharaka Nithi": ["Chuka/Igambang'ombe","Maara","Tharaka North","Tharaka South"],
  "Embu": ["Manyatta","Mbeere North","Mbeere South","Runyenjes"],
  "Kitui": ["Ikutha","Katulani","Kitui Central","Kitui East","Kitui Rural","Kitui South","Kitui West","Lower Yatta","Mwingi Central","Mwingi North","Mwingi West"],
  "Machakos": ["Kathiani","Machakos Town","Masinga","Matungulu","Mavoko","Mwala","Yatta"],
  "Makueni": ["Kaiti","Kibwezi East","Kibwezi West","Kilome","Makueni","Mbooni"],
  "Nyandarua": ["Kinangop","Kipipiri","Ndaragwa","Ol Kalou","Ol Joro Orok"],
  "Nyeri": ["Kieni East","Kieni West","Mathira East","Mathira West","Mukurweini","Nyeri Town","Othaya","Tetu"],
  "Kirinyaga": ["Gichugu","Kirinyaga Central","Mwea East","Mwea West","Ndia"],
  "Murang'a": ["Gatanga","Kahuro","Kandara","Kangema","Kigumo","Kiharu","Mathioya","Murang'a South"],
  "Kiambu": ["Gatundu North","Gatundu South","Githunguri","Juja","Kabete","Kiambaa","Kiambu","Kikuyu","Lari","Limuru","Ruiru","Thika Town"],
  "Turkana": ["Loima","Turkana Central","Turkana East","Turkana North","Turkana South","Turkana West"],
  "West Pokot": ["Central Pokot","Kacheliba","Kipkomo","Pokot South"],
  "Samburu": ["Samburu East","Samburu North","Samburu West"],
  "Trans Nzoia": ["Cherangany","Endebess","Kiminini","Kwanza","Trans Nzoia East","Trans Nzoia West"],
  "Uasin Gishu": ["Ainabkoi","Kapseret","Kesses","Moiben","Soy","Turbo"],
  "Elgeyo Marakwet": ["Keiyo North","Keiyo South","Marakwet East","Marakwet West"],
  "Nandi": ["Aldai","Chesumei","Emgwen","Mosop","Nandi Hills","Tindiret"],
  "Baringo": ["Baringo Central","Baringo North","Baringo South","Eldama Ravine","Mogotio","Tiaty"],
  "Laikipia": ["Laikipia Central","Laikipia East","Laikipia North","Laikipia West","Nyahururu"],
  "Nakuru": ["Bahati","Gilgil","Kuresoi North","Kuresoi South","Molo","Naivasha","Nakuru Town East","Nakuru Town West","Njoro","Rongai","Subukia"],
  "Narok": ["Emurua Dikirr","Kilgoris","Narok East","Narok North","Narok South","Narok West"],
  "Kajiado": ["Isinya","Kajiado Central","Kajiado East","Kajiado North","Kajiado West","Loitokitok","Mashuuru"],
  "Kericho": ["Ainamoi","Belgut","Buret","Kipkelion East","Kipkelion West","Soin/Sigowet"],
  "Bomet": ["Bomet Central","Bomet East","Chepalungu","Konoin","Sotik"],
  "Kakamega": ["Butere","Ikolomani","Khwisero","Likuyani","Lugari","Lurambi","Malava","Matungu","Mumias East","Mumias West","Navakholo","Shinyalu"],
  "Vihiga": ["Emuhaya","Hamisi","Luanda","Sabatia","Vihiga"],
  "Bungoma": ["Bumula","Kabuchai","Kanduyi","Kimilili","Mt Elgon","Sirisia","Tongaren","Webuye East","Webuye West"],
  "Busia": ["Budalang'i","Butula","Funyula","Nambale","Teso North","Teso South"],
  "Siaya": ["Alego Usonga","Bondo","Gem","Rarieda","Ugenya","Ugunja"],
  "Kisumu": ["Kisumu Central","Kisumu East","Kisumu West","Muhoroni","Nyakach","Nyando","Seme"],
  "Homa Bay": ["Homa Bay Town","Kabondo Kasipul","Karachuonyo","Kasipul","Mbita","Ndhiwa","Rangwe","Suba North","Suba South"],
  "Migori": ["Awendo","Kuria East","Kuria West","Mabera","Ntimaru","Rongo","Suna East","Suna West","Uriri"],
  "Kisii": ["Bobasi","Bomachoge Borabu","Bomachoge Chache","Bonchari","Etago","Kitutu Chache North","Kitutu Chache South","Nyaribari Chache","Nyaribari Masaba","South Mugirango"],
  "Nyamira": ["Borabu","Manga","Masaba North","Nyamira North","Nyamira South"],
  "Nairobi": ["Dagoretti North","Dagoretti South","Embakasi Central","Embakasi East","Embakasi North","Embakasi South","Embakasi West","Kabete","Kasarani","Kibra","Langata","Makadara","Mathare","Roysambu","Ruaraka","Starehe","Westlands"]
};

export const COUNTY_NAMES = Object.keys(KENYA_COUNTIES).sort();